services:
  core:
    image: bletvaska/gaussgame-core
#    build: ..
    depends_on:
      - mosquitto
    restart: always
    environment:
      TAPGAME_BROKER: mosquitto
      TAPGAME_DB_URI: sqlite:///app/db.sqlite

  ui:
    image: dillir/gauss-frontend
    depends_on:
      - mosquitto
      - core
    restart: always
    ports:
      - 80:80


  mosquitto:
    # url: https://hub.docker.com/_/eclipse-mosquitto
    image: eclipse-mosquitto:2.0-openssl
    restart: always
    ports:
    - 8000:8000
    - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/config:ro


  # db:
  #   # url: https://hub.docker.com/r/bitnami/postgresql
  #   image: postgress:latest
  #   volumes:
  #   - postgresql:/bitnami/postgresql
  #   # ports:
  #   # - 5432:5432
  #   environment:
  #   - POSTGRESQL_PASSWORD=secret
  #   - POSTGRESQL_USERNAME=boris
  #   - POSTGRESQL_DATABASE=game

#  mqtt-explorer:
#    image: smeagolworms4/mqtt-explorer
#    ports:
#    - 4000:4000 



#volumes:
#  postgresql:
