services:
  core:
    image: bletvaska/gaussgame-core
#    build: ..
    depends_on:
      - mosquitto
    restart: always
    environment:
      TAPGAME_BROKER: mosquitto
      TAPGAME_DB_URI: sqlite:///app/db.sqlite
    volumes:
      - db:/app


  bridge:
    image: bletvaska/gaussgame-core
    depends_on:
    - mosquitto
    restart: always
    environment:
      TAPGAME_BROKER: mosquitto
    devices:
    - /dev/gpiomem:/dev/gpiomem
    command: tapbridge


  ui:
    image: dillir/gauss-frontend
    depends_on:
      - mosquitto
      - core
    restart: always
    ports:
      - 80:80


  mosquitto:
    # url: https://hub.docker.com/_/eclipse-mosquitto
    image: eclipse-mosquitto:2.0-openssl
    restart: always
    ports:
    - 8000:8000
    - 1883:1883
    volumes:
      - ./mosquitto:/mosquitto/config:ro


volumes:
  db: {}
  