services:

  z2m:
    image: koenkk/zigbee2mqtt:2.1
    restart: always
    ports:
      - 8080:8080
    # depends_on:
      # - mosquitto
    # privileged: true
    volumes:
      - ./z2m:/app/data/
    devices:
    #  - /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_067e5cc0ce91ed11b97ccad13b20a988-if00-port0:/dev/ttyUSB0
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CDFEF8E-if00:/dev/ttyUSBO
    environment:
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ember
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=${MQTT_SERVER}
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=${MQTT_USER}
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=${MQTT_PASSWORD}
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=steelpark/iotcorner/z2m

