services:
  mosquitto:
    # url: https://hub.docker.com/_/eclipse-mosquitto
    image: eclipse-mosquitto:2.0-openssl
    restart: always
    ports:
    - 1883:1883
    - 8000:8000
    volumes:
      - ./mosquitto:/mosquitto/config:ro

  z2m:
    image: koenkk/zigbee2mqtt:1.42.0
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mosquitto
    privileged: true
    volumes:
      - ./z2m:/app/data/
    # devices:
      # - /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_067e5cc0ce91ed11b97ccad13b20a988-if00-port0:/dev/ttyUSB0
    environment:
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER=ember
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT=/dev/ttyUSB0
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER=mqtt://78a616db237848caafd6d609ef8f627a.s1.eu.hivemq.cloud:8883
      - ZIGBEE2MQTT_CONFIG_MQTT_USER=maker
      - ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD=Kulturpark13
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=kulturpark/iotcorner/z2m

  app:
    image: nginx
    #build: app/
    restart: always
    ports:
    - 80:80
    depends_on:
      - mosquitto
    volumes:
      - ./app/src:/usr/share/nginx/html

  # watchtower:


# volumes:
  # z2m:
  # app:
