homeassistant:
  enabled: false
frontend:
  enabled: true
mqtt:
  base_topic: steelpark/iotcorner/z2m
  server: mqtts://78a616db237848caafd6d609ef8f627a.s1.eu.hivemq.cloud:8883
  user: maker
  password: Kulturpark13
serial:
  port: /dev/ttyUSB0
  adapter: ember
advanced:
  log_output:
    - console
  network_key:
    - 218
    - 45
    - 52
    - 165
    - 136
    - 64
    - 92
    - 163
    - 73
    - 101
    - 198
    - 223
    - 59
    - 164
    - 166
    - 126
  pan_id: 16113
  ext_pan_id:
    - 93
    - 127
    - 209
    - 13
    - 9
    - 101
    - 119
    - 165
device_options: {}
devices:
  '0x08ddebfffed746e0':
    friendly_name: socket-4
  '0x8c65a3fffe86c96e':
    friendly_name: socket-2
  '0x08ddebfffed74f92':
    friendly_name: socket-3
  '0xd44867fffe555688':
    friendly_name: socket-1
  '0x8c65a3fffe86d52b':
    friendly_name: socket-5
version: 4
